### ISSUE TITLE
Add CNS: Coineus

### ISSUE THREAD

**Issue by CryptoJoshua** [voltfinance/swap-default-token-list#3]
- [x] I understand that token listing is not required to use the Uniswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0xc2E299b47398963c618De5b05C6BdeCd4cc64022
Token Name (from contract): Coineus
Token Decimals (from contract): 18
Token Symbol (from contract): CNS
Uniswap V2 Pair Address of Token: 0x0f2e60b799f2237633754f8eec7970c125e15d75

Link to the official homepage of token: coineus.app
Link to CoinMarketCap or CoinGecko page of token: n/a

**Comment by JanOwiesniak** [comment]
[Related PR](https://github.com/voltfinance/swap-default-token-list/pull/4)
